apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: c.large
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 2
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: c.medium
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 4
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: c.small
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 1
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 2Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: c.xlarge
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 4
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 8Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: c.xsmall
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 4
    numa:
      guestMappingPassthrough: {}
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: g.medium
spec:
  cpu:
    guest: 4
  gpus:
  - deviceName: nvidia.com/A400
    name: GPU1
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: g.xlarge
spec:
  cpu:
    guest: 4
  gpus:
  - deviceName: nvidia.com/A400
    name: GPU1
  memory:
    guest: 16Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: g.xsmall
spec:
  cpu:
    guest: 4
  gpus:
  - deviceName: nvidia.com/A400
    name: GPU1
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: m.large
spec:
  cpu:
    guest: 2
  memory:
    guest: 8Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: m.medium
spec:
  cpu:
    guest: 4
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: m.small
spec:
  cpu:
    guest: 2
  memory:
    guest: 2Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: m.xlarge
spec:
  cpu:
    guest: 4
  memory:
    guest: 16Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: m.xsmall
spec:
  cpu:
    guest: 4
  memory:
    guest: 4Gi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: r.large
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 2
  memory:
    guest: 16Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: r.medium
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 4
  memory:
    guest: 4Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: r.xlarge
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 4
  memory:
    guest: 32Gi
    hugepages:
      pageSize: 2Mi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachineFlavor
metadata:
  name: r.xsmall
spec:
  cpu:
    dedicatedCPUPlacement: true
    guest: 1
  memory:
    guest: 512M
    hugepages:
      pageSize: 2Mi
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: linux.cirros
spec:
  devices:
    preferredCdromBus: virtio
    preferredDiskBus: virtio
    preferredRng: {}
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: linux.fedora
spec:
  devices:
    preferredCdromBus: virtio
    preferredDiskBus: virtio
    preferredRng: {}
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: linux.rhel9
spec:
  cpu:
    preferredCPUTopology: preferCores
  devices:
    preferredCdromBus: virtio
    preferredDiskBus: virtio
    preferredRng: {}
---
apiVersion: flavor.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: windows.windows10
spec:
  clock:
    preferredClockOffset:
      utc: {}
    preferredTimer:
      hpet:
        present: false
      hyperv: {}
      pit:
        tickPolicy: delay
      rtc:
        tickPolicy: catchup
  cpu:
    preferredCPUTopology: preferSockets
  devices:
    preferredDiskBus: sata
    preferredInterfaceModel: e1000
    preferredTPM: {}
  features:
    preferredAcpi: {}
    preferredApic: {}
    preferredHyperv:
      relaxed: {}
      spinlocks:
        spinlocks: 8191
      vapic: {}
    preferredSmm: {}
  firmware:
    preferredUseEfi: true
    preferredUseSecureBoot: true
