apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../baseFlavors/c
- ../baseFlavors/m

nameSuffix: .small

patches:
- path: c.yaml
  target:
      name: .*
- path: m.yaml
  target:
    name: m
