apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../basePreferences/windows

nameSuffix: .windows10

patches:
  - path: VirtualMachinePreference.yaml
    target:
      name: windows
